# Services for Heating Manager

set_boost:
  name: Set Boost
  description: Enable boost mode for a specific room
  fields:
    zone_id:
      name: Zone ID
      description: The ID of the zone (e.g., 'downstairs', 'upstairs')
      required: true
      example: "downstairs"
      selector:
        text:
    room_id:
      name: Room ID
      description: The ID of the room (e.g., 'living_room', 'bedroom')
      required: true
      example: "living_room"
      selector:
        text:
    duration:
      name: Duration
      description: Duration of boost in minutes (default 30)
      required: false
      example: 60
      selector:
        number:
          min: 1
          max: 480
          unit_of_measurement: minutes
    temperature:
      name: Temperature
      description: Target temperature during boost (default is current schedule + 2°C)
      required: false
      example: 22
      selector:
        number:
          min: 5
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

clear_boost:
  name: Clear Boost
  description: Disable boost mode for a specific room
  fields:
    zone_id:
      name: Zone ID
      description: The ID of the zone
      required: true
      example: "downstairs"
      selector:
        text:
    room_id:
      name: Room ID
      description: The ID of the room
      required: true
      example: "living_room"
      selector:
        text:

set_mode:
  name: Set Mode
  description: Set the heating mode (schedule or away)
  fields:
    mode:
      name: Mode
      description: The heating mode to set
      required: true
      example: "schedule"
      selector:
        select:
          options:
            - label: "Schedule"
              value: "schedule"
            - label: "Away"
              value: "away"

ignore_manual_override:
  name: Ignore Manual Override
  description: Configure whether to ignore manual TRV adjustments for a room
  fields:
    zone_id:
      name: Zone ID
      description: The ID of the zone
      required: true
      example: "downstairs"
      selector:
        text:
    room_id:
      name: Room ID
      description: The ID of the room
      required: true
      example: "living_room"
      selector:
        text:
    ignore:
      name: Ignore
      description: Whether to ignore manual overrides (true) or respect them (false)
      required: true
      example: true
      selector:
        boolean:
